version: '3'
services:

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    tty: true
    volumes:
      - ./:/var/www/app
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/app/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
